// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq582jPdP_7m8FLMj5sp4jMqh2q2oaPpk',
    appId: '1:321017700916:web:0a1198d8b3dba3c254a061',
    messagingSenderId: '321017700916',
    projectId: 'study-app-5724b',
    authDomain: 'study-app-5724b.firebaseapp.com',
    storageBucket: 'study-app-5724b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjhbFJ7joTigr2_rfSY3Bug6qbHNK4mMU',
    appId: '1:321017700916:android:ac81aa482ae6306b54a061',
    messagingSenderId: '321017700916',
    projectId: 'study-app-5724b',
    storageBucket: 'study-app-5724b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAZJKr__JsA4wKFp9eiemsKs3hfDNrk3A',
    appId: '1:321017700916:ios:07f50c4ab6f0f33e54a061',
    messagingSenderId: '321017700916',
    projectId: 'study-app-5724b',
    storageBucket: 'study-app-5724b.appspot.com',
    iosClientId: '321017700916-lrvt7pche7pgr93pk4mq6k77g7g7r81t.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAZJKr__JsA4wKFp9eiemsKs3hfDNrk3A',
    appId: '1:321017700916:ios:07f50c4ab6f0f33e54a061',
    messagingSenderId: '321017700916',
    projectId: 'study-app-5724b',
    storageBucket: 'study-app-5724b.appspot.com',
    iosClientId: '321017700916-lrvt7pche7pgr93pk4mq6k77g7g7r81t.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
